/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Docs: typeof import('./src/views/Docs/Docs.vue')['default']
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HomeLoading: typeof import('./src/components/HomeLoading.vue')['default']
    OverallLayout: typeof import('./src/views/Home/OverallLayout.vue')['default']
    Root: typeof import('./src/views/Root/Root.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Welcome: typeof import('./src/views/Home/Welcome.vue')['default']
  }
}
